# -*- coding: utf-8 -*-
"""TASKS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OoG2NwqtRf5l6vs2CeyXM9frCVGBzuUe
"""

import re
a=input('Enter username:')
l=[]
d={}
s='^[a-z 0-9]+[\.-_]?[a-z ]+[@]\w+[.]\w{2,3}$'
if re.search(s,a):
    print('VALID EMAIL ID')
    l.append(a)
    b=input('Enter password:')
    p='[A-Z]+|[a-z\d]+|[@#$&*]?'
    if len(b)<8:
        print('Invalid')
    if   re.search(p,b):
        print("Valid Password")
        l.append(b)
    c=input("Do you wish to login?")
    if c=="yes":
         x=input("Enter username:")
         if x in d:
            print("Welcome")
         else:
             print("Please register here:")
             x=input("Enter new username:")
             y=input("Enter new password:")
             l.append(x)
             l.append(y)
             d.update({x:y})
    if c=="Forgot password":
        x=input("Enter username:")
        if x in d:
            print(d.get(x))
        else:
            print("Kindy register")
else:
    print('INVALID EMAIL ID')
    print("Do you want to register:")